const APP_ACTIONS = {
 CONFIG_LOADED: 'CONFIG_LOADED',
	REQUEST_MERCHANTS: 'REQUEST_MERCHANTS',
	RECEIVE_MERCHANTS: 'RECEIVE_MERCHANTS',
	REQUEST_MERCHANT: 'REQUEST_MERCHANT',
	RECEIVE_MERCHANT: 'RECEIVE_MERCHANT',
	RESET_MERCHANT: 'RESET_MERCHANT',
	CREATE_MERCHANT: 'CREATE_MERCHANT',
	CREATED_MERCHANT: 'CREATED_MERCHANT',
	UPDATE_CREATE_REQUEST_STATUS: 'UPDATE_CREATE_REQUEST_STATUS',
	UPDATE_MERCHANT: 'UPDATE_MERCHANT',
	UPDATED_MERCHANT: 'UPDATED_MERCHANT',
	UPDATE_EDIT_REQUEST_STATUS: 'UPDATE_EDIT_REQUEST_STATUS',
	DELETE_MERCHANT: 'DELETE_MERCHANT',
	DELETED_MERCHANT: 'DELETED_MERCHANT'
}

export default {
 ...APP_ACTIONS
};
